### ISSUE TITLE
TWSocket in C++ Builder (XE8)

### ISSUE THREAD

**Issue by fvpalha** [ashumkin/OverbyteICS#1]
Hi.

I need to use the TWSocket in C++ Builder (XE8), but after the install only Delphi components are visibles.

How I can to use the components in C++ Builder?

Regards.

**Comment by ashumkin** [comment]
I'm sorry, but I have no idea ;) (I'm a Delphi developer, if I may say so)
Please, can you ask OverbyteICS components author http://www.overbyte.be/?
I have just copied his SVN repository to use it as a Git repository.

**Comment by fvpalha** [comment]
Thank you @ashumkin
